### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by abb1991** [devsagul/prj-rev-bwfs-dasmoto#1]
Your HTML looks really solid. I like your consistent white spacing, indentation, and encapsulation through divs. It makes your code very readable!

I noticed you added classes to your elements, when would you want to use an id rather than a class?

**Comment by devsagul** [comment]
I would like to use id only if I know for sure that I will not use the same styling again and if the use of an id would make my code more readable. Most common case for me to use an id when I have multiple objects with shared styling but some properties would differ from object to object e.g. I have class "button" for all the buttons on my page because they have the same radius, border etc., but for example stop button is red and play button is green, I would consider using ids like "stop" and "play"
